services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        ports:
        # Interface sécurisée (HTTPS)
        - "9443:9443"
        # Décommentez la ligne suivante si vous voulez aussi l'HTTP legacy
        # - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
  portainer_data:
    external: true    

